name : rwgps_report

on:
  schedule:
    - cron : '0 15 * * 1,3,5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-python@v2
        with:
          python-version: 3.x
      - name: Run RWGPS script
        env:
          user_email: ${{ secrets.user_email }}
          email_token: ${{ secrets.email_tocken }}
          api_key: ${{ secrets.api_key }}
          api_token: ${{ secrets.api_token }}
          url_user: ${{ secrets.url_user }}
          url_trips: ${{ secrets.url_trips }}
        run: python rwgps.py
