name : rwgps_report

on:
  schedule:
    - cron : '0 15 * * 1,3,5'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: 3.x
      - name: install packages
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run rwgps
        env:
          user_email: ${{ secrets.user_email }}
          email_token: ${{ secrets.email_token }}
          api_key: ${{ secrets.api_key }}
          api_token: ${{ secrets.api_token }}
          url_user: ${{ secrets.url_user }}
          url_trips: ${{ secrets.url_trips }}
        run: python rwgps.py
